# Generated by Django 3.0.3 on 2020-02-26 16:44

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(null=True, validators=[posts.models.Posts.min_length_check]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=150, null=True, validators=[posts.models.Posts.min_length_check]),
        ),
    ]
